# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-02 07:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=64, unique=True)),
                ('password', models.CharField(max_length=256)),
                ('name', models.CharField(max_length=32)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
